#!/bin/sh

# Clean up all build artifacts
rm -rf src/Imath/build
rm -rf src/Imath/build/initial-cache.cmake
rm -rf src/Makevars
rm -rf src/Makevars.win
rm -rf inst/lib
rm -rf inst/include
rm -rf config.log
rm -rf config.status
rm -rf autom4te.cache
rm -rf configure~